#pragma once
#include <allegro.hpp>
#include <zlib.hpp>

#include <afterimage.hpp>
#include <ai.hpp>
#include <anim.hpp>
#include <arith.hpp>
#include <array.hpp>
#include <bg.hpp>
#include <bgm.hpp>
#include <charsel.hpp>
#include <clipboard.hpp>
#include <command.hpp>
#include <common.hpp>
#include <controller.hpp>
#include <date.hpp>
#include <ebcommon.hpp>
#include <explod.hpp>
#include <font.hpp>
#include <game.hpp>
#include <kbi.hpp>
#include <pallete.hpp>
#include <player.hpp>
#include <projectile.hpp>
#include <sound.hpp>
#include <sprite.hpp>
#include <state.hpp>
#include <system.hpp>
#include <trigger.hpp>
#include <txtparse.hpp>