#pragma once
#include <_MUGEN_TYPES.hpp>

#include <arith.hpp>
#include <array.hpp>

namespace mugen20414::state::trigger {
	using namespace mugen20414::arith;
	using namespace mugen20414::array;

	enum class TriggerId {
		kTrigIdTime              = 0,
		kTrigIdAnimTime          = 1,
		kTrigIdAnimElem          = 2,
		kTrigIdAnim              = 3,
		kTrigIdPos               = 4,
		kTrigIdScreenPos         = 5,
		kTrigIdVel               = 6,
		kTrigIdTimeMod           = 7,
		kTrigIdP2Dist            = 8,
		kTrigIdP2BodyDist        = 9,
		kTrigIdP2Life            = 10,
		kTrigIdFrondEdgeDist     = 11,
		kTrigIdFrontEdgeBodyDist = 11,
		kTrigIdBackEdgeBodyDist  = 12,
		kTrigIdBackEdgeDist      = 12,
		kTrigIdLife              = 15,
		kTrigIdLifeMax           = 16,
		kTrigIdPower             = 17,
		kTrigIdPowerMax          = 18,
		kTrigIdAlive             = 19,
		kTrigIdCommand           = 20,
		kTrigIdHitCount          = 30,
		kTrigIdUniqHitCount      = 31,
		kTrigIdMoveHit           = 32,
		kTrigIdMoveGuarded       = 33,
		kTrigIdMoveContact       = 34,
		kTrigIdMoveReversed      = 35,
		kTrigIdInGuardDist       = 36,
		kTrigIdStateNo           = 40,
		kTrigIdPrevStateNo       = 41,
		kTrigIdP2StateNo         = 42,
		kTrigIdStateType         = 43,
		kTrigIdP2StateType       = 44,
		kTrigIdMoveType          = 45,
		kTrigIdP2MoveType        = 46,
		kTrigIdCtrl              = 47,
		kTrigIdHitDefAttr        = 48,
		kTrigIdRandom            = 51,
		kTrigIdNumProj           = 60,
		kTrigIdProjHit           = 62,
		kTrigIdProjGuarded       = 63,
		kTrigIdProjContact       = 64,
		kTrigIdName              = 90,
		kTrigIdP1Name            = 90,
		kTrigIdP2Name            = 91,
		kTrigIdP3Name            = 92,
		kTrigIdP4Name            = 93,
		kTrigIdAuthorName        = 94,
		kTrigIdNumPartner        = 95,
		kTrigIdNumEnemy          = 96,
		kTrigIdID                = 97,
		kTrigIdFacing            = 99,
		kTrigIdHitFall           = 100,
		kTrigIdHitShakeOver      = 101,
		kTrigIdHitOver           = 102,
		kTrigIdHitVel            = 103,
		kTrigIdHitPauseTime      = 104,
		kTrigIdCanRecover        = 105,
		kTrigIdPalNo             = 107,
		kTrigIdWinPerfect        = 108,
		kTrigIdWin               = 109,
		kTrigIdLose              = 110,
		kTrigIdDrawGame          = 111,
		kTrigIdMatchOver         = 112,
		kTrigIdGameTime          = 113,
		kTrigIdRoundNo           = 114,
		kTrigIdRoundState        = 115,
		kTrigIdMatchNo           = 116,
		kTrigIdRoundsExisted     = 117,
		kTrigIdTeamSide          = 120,
		kTrigIdTeamMode          = 121,
		kTrigIdIsHomeTeam        = 122,
		kTrigIdNumExplod         = 150,
		kTrigIdNumTarget         = 160,
		kTrigIdGetHitVar         = 180,
		kTrigIdConst             = 181,
		kTrigIdTicksPerSecond    = 190,
		kTrigIdIsHelper          = 201,
		kTrigIdNumHelper         = 202,
		kTrigIdParentDist        = 203,
		kTrigIdRootDist          = 204,
		kTrigIdStandBy           = 205,
		kTrigIdPi                = 300,
		kTrigIdE                 = 301,
		kTrigIdIfElse            = 305,
		kTrigIdLog               = 310,
		kTrigIdSin               = 320,
		kTrigIdCos               = 321,
		kTrigIdTan               = 322,
		kTrigIdASin              = 323,
		kTrigIdACos              = 324,
		kTrigIdATan              = 325,
		kTrigIdExp               = 326,
		kTrigIdLn                = 327,
		kTrigIdAbs               = 328,
		kTrigIdFloor             = 329,
		kTrigIdCeil              = 330,
		kTrigIdAnimElemTime      = 331,
		kTrigIdAnimExist         = 332,
		kTrigIdSelfAnimExist     = 333,
		kTrigIdPlayerIDExist     = 334,
		kTrigIdIsHelper_ID       = 335,
		kTrigIdNumHelper_ID      = 336,
		kTrigIdProjHitTime       = 337,
		kTrigIdProjGuardedTime   = 338,
		kTrigIdProjContactTime   = 339,
		kTrigIdNumProjID         = 340,
		kTrigIdNumExplod_ID      = 341,
		kTrigIdNumTarget_ID      = 342,
		kTrigIdVar               = 343,
		kTrigIdFVar              = 344,
		kTrigIdSysVar            = 345,
		kTrigIdSysFVar           = 346,
		kTrigIdProjCancelTime    = 347,
		kTrigIdAnimElemNo        = 348
	};
	enum class RedirectId {
		kRedirIdNone      = 0,
		kRedirIdParent    = 1,
		kRedirIdRoot      = 2,
		kRedirIdHelper    = 3,
		kRedirIdTarget    = 4,
		kRedirIdPartner   = 5,
		kRedirIdEnemy     = 6,
		kRedirIdEnemyNear = 7,
		kRedirIdPlayerID  = 8
	};
	enum class GetHitVarId{
		kGHVIdXVelAdd = 0,
		kGHVIdYVelAdd,
		kGHVIdType,
		kGHVIdAnimType,
		kGHVIdAirType,
		kGHVIdGroundType,
		kGHVIdDamage,
		kGHVIdHitCount,
		kGHVIdFallCount,
		kGHVIdHitShakeTime,
		kGHVIdHitTime,
		kGHVIdSlideTime,
		kGHVIdCtrlTime,
		kGHVIdRecoverTime,
		kGHVIdXOff,
		kGHVIdYOff,
		kGHVIdZOff,
		kGHVIdXVel,
		kGHVIdYVel,
		kGHVIdYAccel,
		kGHVIdChainID,
		kGHVIdGuarded,
		kGHVIdIsBound,
		kGHVIdFall,
		kGHVIdFallDamage,
		kGHVIdFallXVel,
		kGHVIdFallYVel,
		kGHVIdFallRecover,
		kGHVIdFallTime,
		kGHVIdFallRecoverTime,
		kGHVIdFallKill,
		kGHVIdFallEnvShakeTime,
		kGHVIdFallEnvShakeDir,
		kGHVIdFallEnvShakeAmpl,
		kGHVIdFallEnvShakeFreq,
		kGHVIdFallEnvShakePhase,
	};
	enum class SpecialFlagId {
		kSpecIdIntro          = 0,
		kSpecIdRoundNotOver   = 1,
		kSpecIdNoKO           = 2,
		kSpecIdNoKOSnd        = 3,
		kSpecIdNoKOSlow       = 4,
		kSpecIdNoMusic        = 5,
		kSpecIdGlobalNoShadow = 6,
		kSpecIdTimerFreeze    = 7,
		kSpecIdNoBarDisplay   = 8,
		kSpecIdNoBG           = 9,
		kSpecIdNoFG           = 10,
		kSpecIdNoStandGuard   = 16,
		kSpecIdNoCrouchGuard  = 17,
		kSpecIdNoAirGuard     = 18,
		kSpecIdNoAutoTurn     = 19,
		kSpecIdNoShadow       = 20,
		kSpecIdNoJuggleCheck  = 21,
		kSpecIdNoWalk         = 22,
		kSpecIdNoUnguardable  = 23,
		kSpecIdInvisible      = 24
	};

	struct Trigger {
		TriggerId trigID;
		RedirectId redirectID;
		Expression redirectArg;
		Comparator compareStyle;
		BOOL isFloat;
		ExprValue trigArgs[6];
		const char* trigStrArg;
	};
}